apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: single-binary
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: http-metrics
      nodePort: 31100
