---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pve-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgAyKkW7AOgRIaS/9uQGwt/ZKQTzy79CCyKBfsvslntPreQL8EsVsOEwJrZUdkhwRutVUrJqyQpoSooS0twUiGCeGjxyQwNnic/p9a/J54nSGwIK6ZEIe0J6m5h2lKBx6fl/A6nQwc+rc4w3NE8L3ae9SVqZLuRgWaIdHOMKgiv7AtJ6lYvgRuWN2yJ4QcD8WbXF86ZCb/dYruE8XjcYYNnmpHOpL2LuV2Cgs9lk5K5+W8UFSwJUZNSlrHOZ2OrMehVI6679Ivg6hFUmKMAtv2fDGC4zU5/imtkLSihbqjFviS5kXGy8slYm5FJdoRFzhym//Y3A9p5M7e6OB/kkqLPbl9BgAsrtrR/mYH2+d0wYSdYG9Hbah+gYy0ynVmPHU5v54GnNKPSypYIRvgL1z2xDNJNxt6P8b852QdoVDJn/e3FSgQOx3Ji9B981BS+LBjyKTm1laqagjn2JG2mgEACmrJ8e9BzJ1jgGcoDVL/kSBh6Z+JDJZwsWmLNmzrcEujpxk5HCuxIJCxV3x6UopV3Ge4OHrkbIX/yymxElQWwcwJcZUnB86xO54u7rkVRbrb+fVg/0jrf7fqGKDgUvFHIfSJlCzAyszZoAzb/JxyJv9sjgugtBXQNOj25HyhNYqjfeeSWJzxp30MrKtlIuSterKHUkQXoRrBV8HzCc10lpP9UMgcxQSDMzDoQqhmfST53NGhWOcdqLkpmlOkkdWmNRgWtKmUoWrYUJnzA8ZptaDeRZV/+m8/jeX6VQJZkTMZJnvGqcisO4pvSc1/4d1rmPQrmlXN4QgFWho7P32QN0Eh26MiVYKsZz1OMfmsrwrZGy7aTthiHshVp8QSlpP2QRcoqSgTiP
  template:
    metadata:
      creationTimestamp: null
      name: pve-exporter-config
      namespace: monitoring
    type: Opaque
