apiVersion: v2
name: sealed-secrets
description: Sealed Secrets controller for committing encrypted secrets to Git
version: 0.1.0
dependencies:
  - name: sealed-secrets
    version: "2.18.5"
    repository: https://bitnami-labs.github.io/sealed-secrets
